apiVersion: apps/v1
kind: Deployment
metadata:
  name: <chart>-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: <chart>-operator
  template:
    metadata:
      labels:
        name: <chart>-operator
    spec:
      containers:
        - name: <chart>-operator
          image: quay.io/<namespace>/<chart>-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
