apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.consoleConfig.name}}
  namespace: {{ .Values.shared.namespace }}
  labels:
  # at present, these are the labels 
  # from the console, not the shared labels
  {{- range .Values.shared.labels }}
  {{ .name }}: {{ .value }}
  {{- end }}
data:
  # embedded yaml file
  console-config.yaml: |
    kind: {{ .Values.consoleConfig.data.kind }}
    apiVersion: {{ .Values.consoleConfig.data.apiVersion }}
    auth:
      clientID: {{ .Values.auth.clientID }}
      clientSecretFile: {{ .Values.auth.clientSecretFile }}
      logoutRedirect: {{ .Values.auth.logoutRedirect }}
      oauthEndpointCAFile: {{ .Values.auth.oauthEndpointCAFile }}
    clusterInfo:
      consoleBaseAddress: {{ .Values.clusterInfo.consoleBaseAddress }}
      consoleBasePath: {{ .Values.clusterInfo.consoleBasePath }}
      developerConsolePublicURL: {{ .Values.clusterInfo.developerConsolePublicURL }}
      masterPublicURL: {{ .Values.clusterInfo.masterPublicURL }}
    customization:
      branding: {{ .Values.customization.branding }}
      documentationBaseURL: {{ .Values.customization.documentationBaseURL }}
    servingInfo:
      bindAddress: {{ .Values.servingInfo.bindAddress }}
      certFile: {{ .Values.servingInfo.certFile }}
      keyFile: {{ .Values.servingInfo.keyFile }}

